[package]
name = "ww-effects"
version = "0.1.0-dev"
authors = ["Dyson Dyson <dyson.dyson@icloud.com>"]
edition = "2021"
rust-version = "1.65"
description = "The effects for Winter WonderLights."
repository = "https://github.com/DoctorDalek1963/winter-wonderlights"
license = "GPL-3.0"

[dependencies]
async-trait.workspace = true
egui.workspace = true
heck = "0.4.1"
ron.workspace = true
serde.workspace = true
strum.workspace = true
tokio.workspace = true
ww-driver-trait = { path = "../ww-driver-trait" }

# impl
glam = { workspace = true, optional = true, features = ["serde"] }
rand = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
ww-frame = { path = "../ww-frame", optional = true }
ww-gift-coords = { path = "../ww-gift-coords", optional = true }

[features]
default = ["impl"]
bench = []
impl = ["dep:glam", "dep:rand", "dep:tracing", "dep:ww-frame", "dep:ww-gift-coords"]

[dev-dependencies]
insta.workspace = true
ww-driver-impl = { path = "../ww-driver-impl", features = ["test"] }
