[package]
name = "ww-effects"
version = "0.1.0-dev"
authors = ["Dyson Dyson <dyson.dyson@icloud.com>"]
edition = "2021"
rust-version = "1.65"
description = "The effects for Winter WonderLights."
repository = "https://github.com/DoctorDalek1963/winter-wonderlights"
license = "GPL-3.0"

[dependencies]
async-trait = "0.1.64"
egui = "0.20.1"
heck = "0.4.1"
ron = "0.8.0"
serde = { version = "1.0.152", features = ["derive"] }
strum = { version = "0.24.1", features = ["derive"] }
tokio = { version = "1.25.0", features = ["macros", "rt", "time", "sync"] }
ww-driver-trait = { path = "../ww-driver-trait" }

# impl
glam = { version = "0.22.0", optional = true, features = ["rand", "serde"] }
rand = { version = "0.8.5", optional = true }
tracing = { version = "0.1.37", optional = true }
ww-frame = { path = "../ww-frame", optional = true }
ww-gift-coords = { path = "../ww-gift-coords", optional = true }

[features]
default = ["impl"]
impl = ["dep:glam", "dep:rand", "dep:tracing", "dep:ww-frame", "dep:ww-gift-coords"]

[dev-dependencies]
insta = { version = "1.26.0", features = ["ron"] }
ww-driver-impl = { path = "../ww-driver-impl", features = ["test"] }
