repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt

  - repo: local
    hooks:
      - id: just-check
        name: just check
        entry: just check
        language: system
        files: '.*\.rs|Cargo.(toml|lock)$'
        pass_filenames: false

      - id: just-build
        name: just build
        entry: just build
        language: system
        files: '.*\.rs|Cargo.(toml|lock)$'
        pass_filenames: false

      - id: just-doc-build
        name: just doc-build
        entry: just doc-build
        language: system
        files: '.*\.rs|Cargo.(toml|lock)$'
        pass_filenames: false

      - id: just-test
        name: just test
        entry: just test
        language: system
        files: '.*\.rs|Cargo.(toml|lock)$'
        pass_filenames: false
