[package]
name = "winter-wonderlights"
version = "0.1.0"
authors = ["Dyson Dyson <dyson.dyson@icloud.com>"]
edition = "2021"
rust-version = "1.65"
description = " A program to render 3D effects on a Christmas tree in real time."
repository = "https://github.com/DoctorDalek1963/winter-wonderlights"
license = "GPL-3.0"

[[bin]]
name = "winter-wonderlights"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.64"
bevy = { version = "0.9.1", optional = true }
bevy_egui = { version = "0.19.0", optional = true }
bincode = "1.3.3"
cfg-if = "1.0.0"
color-eyre = "0.6.2"
egui = "0.20.1"
heck = "0.4.1"
lazy_static = "1.4.0"
rand = "0.8.5"
ron = "0.8.0"
serde = { version = "1.0.152", features = ["derive"] }
smooth-bevy-cameras = { version = "0.7.0", optional = true }
strum = { version = "0.24.1", features = ["derive"] }
tokio = { version = "1.25.0", features = ["macros", "rt", "time", "sync"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[dev-dependencies]
criterion = { version = "0.4.0", features = ["async_tokio"]}
float-cmp = "0.9.0"

[profile.dev.package."*"]
opt-level = 3

[features]
bench = []
virtual-tree = ["dep:bevy", "dep:bevy_egui", "dep:smooth-bevy-cameras"]

[[bench]]
name = "effects"
harness = false
