[graph]
targets = [
	{ triple = "x86_64-unknown-linux-gnu" },
	{ triple = "wasm32-unknown-unknown" },
	{ triple = "arm-unknown-linux-gnueabihf" },
	{ triple = "armv7-unknown-linux-gnueabihf" },
]

[advisories]
yanked = "warn"
# ignore = [
# 	# No part of this project will ever be run on Windows with a custom global
# 	# allocator, so `atty` will never deref an unaligned pointer
# 	"RUSTSEC-2021-0145",
#
# 	# `shlex` v0.1.1 is only used by bindgen in the dev dependencies for nokhwa
# 	# for the scanner client, so no end user could ever be affected by this
# 	"RUSTSEC-2024-0006",
# ]

[licenses]
allow = [
	"Apache-2.0",
	"BSD-2-Clause",
	"BSD-3-Clause",
	"CC0-1.0",
	"GPL-3.0",
	"IJG",
	"ISC",
	"LicenseRef-UFL-1.0",
	"MIT",
	"MIT-0",
	"MPL-2.0",
	"OFL-1.1",
	"OpenSSL",
	"Unicode-3.0",
	"Zlib",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
multiple-versions = "allow"
wildcards = "warn"
allow-wildcard-paths = true

[sources]
allow-git = ["https://github.com/DoctorDalek1963/rpi-ws281x-rust.git"]
