# Taken mostly from: https://github.com/actions-rs/toolchain/issues/216#issuecomment-1291613319

name: 'Setup Rust'
description: 'Setup Rust for the Winter WonderLights CI'

inputs:
  targets:
    required: false
    description: Extra targets for rustup
    default: ''

  components:
    required: false
    description: Extra components for rustup
    default: ''

  cache-key:
    required: false
    description: Extra key to resolve cache
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain nightly

        source "$HOME/.cargo/env"
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

        echo CARGO_TERM_COLOR=always >> $GITHUB_ENV
        echo CARGO_INCREMENTAL=0 >> $GITHUB_ENV
        echo RUST_BACKTRACE=full >> $GITHUB_ENV
        echo RUSTFLAGS=-Dwarnings >> $GITHUB_ENV

        rustc --version --verbose
      shell: bash

    - name: Add rustup targets
      if: "${{ inputs.targets != '' }}"
      run: rustup target add ${{ inputs.targets }}
      shell: bash

    - name: Add rustup components
      if: "${{ inputs.components != '' }}"
      run: rustup component add ${{ inputs.components }}
      shell: bash

    - name: Install cargo-binstall
      run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      shell: bash

    - name: Cargo binstall things
      run: cargo binstall -y just cargo-insta trunk
      shell: bash

    - name: Create .env file
      run: |
        mkdir -p /home/runner/winter-wonderlights-data
        echo 'export DATA_DIR=/home/runner/winter-wonderlights-data'     >  .env
        echo 'export SERVER_SSL_CERT_PATH=/dev/null'                     >> .env
        echo 'export SERVER_SSL_KEY_PATH=/dev/null'                      >> .env
        echo 'export PORT=23120'                                         >> .env
        echo 'export LIGHTS_NUM=250'                                     >> .env
        echo 'export SERVER_URL=ws://localhost:${PORT}'                  >> .env
        echo 'export SCANNER_PORT=23121'                                 >> .env
        echo 'export SCANNER_SERVER_URL=ws://localhost:${SCANNER_PORT}'  >> .env
      shell: bash
