[package]
name = "ww-server"
version = "0.1.0-dev"
authors = ["Dyson Dyson <dyson.dyson@icloud.com>"]
edition = "2021"
description = "The server for Winter WonderLights."
repository = "https://github.com/DoctorDalek1963/winter-wonderlights"
license = "GPL-3.0"

[dependencies]
color-eyre.workspace = true
ron.workspace = true
tiny_http = { version = "0.12.0", features = ["ssl"] }
tracing.workspace = true
tracing-appender = "0.2.2"
tracing-subscriber.workspace = true
tracing-unwrap.workspace = true
ww-driver-trait = { path = "../ww-driver-trait" }
ww-effects = { path = "../ww-effects" }
ww-frame = { path = "../ww-frame" }
ww-shared = { path = "../ww-shared" }
