name: Benchmark

on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: nixbuild/nix-quick-install-action@v27

      - run: nix build .#bench-ci

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1.20
        with:
          name: Benchmark
          tool: 'cargo'
          output-file-path: result/output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
