name: CI

on:
  push:
    branches:
      - main
      - dev/*
      - effect/*
      - driver/*

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/setup
        with:
          components: rustfmt

      - run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/setup
        with:
          components: clippy

      - run: sudo apt install libclang-dev llvm
      - run: just clippy -Dwarnings

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/setup
      - run: just test

  doc-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/setup
      - run: sudo apt install libclang-dev
      - run: just doc-build

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build-type: ['scanner-server', 'scanner-client', 'client', 'driver-debug', 'driver-virtual-tree', 'driver-raspi-ws2811']
        flags: ['', '--release']

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ./.github/setup
      - run: just ci-build ${{ matrix.build-type }} ${{ matrix.flags }}
