name: CI

on:
  push:
    branches:
      - main
      - dev/*
      - effect/*
      - driver/*

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/setup
        with:
          components: rustfmt

      # Debug version information
      - run: |
          rustup --version
          rustfmt --version
          cargo fmt --version

      - run: cargo fmt --all --check

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/setup
        with:
          targets: armv7-unknown-linux-gnueabihf wasm32-unknown-unknown

      - run: sudo apt install libclang-dev
      - run: just check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/setup
        with:
          components: clippy

      - run: just clippy -Dwarnings

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup
      - run: just test

  doc-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup
      - run: sudo apt install libclang-dev
      - run: just doc-build

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        driver: ['driver-debug', 'driver-virtual-tree', 'driver-raspi-ws2811 --target armv7-unknown-linux-gnueabihf']

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/setup
        with:
          targets: armv7-unknown-linux-gnueabihf

      - if: "${{ matrix.driver == 'driver-raspi-ws2811 --target armv7-unknown-linux-gnueabihf' }}"
        run: sudo apt install libclang-dev

      - run: just build "${{ matrix.driver }}"
