name: CI

on:
  push:
    branches:
      - main
      - dev/*
      - effect/*
      - driver/*

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/setup
        with:
          components: rustfmt

      # Debug version information
      - run: |
          rustup --version
          rustfmt --version
          cargo fmt --version

      - run: cargo fmt --all --check

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/setup
        with:
          targets: wasm32-unknown-unknown

      - run: just check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup
      - run: just clippy -Dwarnings

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup
      - run: just test

  doc-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup
      - run: just doc-build

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        driver: ['driver-debug', 'driver-virtual-tree']

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/setup
        with:
          targets: wasm32-unknown-unknown

      - run: just build ${{ matrix.driver }}
